In [2]:
import pandas as pd
import nltk
import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
dataset=pd.read_csv('twitter_training.csv')
test=pd.read_csv('twitter_validation.csv')

In [4]:
print(dataset)

       2401  Borderlands  Positive   
0      2401  Borderlands  Positive  \
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74676  9200       Nvidia  Positive   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
0      I am coming to the borders and I will kill you...     
1      im getting on borderlands and i will kill you ...     
2      im coming on borderlands and i will murder you...     
3      im getting on borderlands 2 and i will murder ...     
4      im getting into borderlands and i can murder y...     
...                                                  ...     
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partiti

In [5]:
xds=dataset[dataset['Borderlands']=='Borderlands']

In [6]:
X_ds=xds.iloc[:,3].values
Y_ds=xds.iloc[:,2].values

In [7]:
print(Y_ds)
print(X_ds)

['Positive' 'Positive' 'Positive' ... 'Positive' 'Positive' 'Positive']
['I am coming to the borders and I will kill you all,'
 'im getting on borderlands and i will kill you all,'
 'im coming on borderlands and i will murder you all,' ...
 'Vaughn Borderlands you deserve the world!!!'
 'Vaughn... Borderlands you do deserve the world!!!'
 'Vaughn Borderlands still deserve the world!!!']


In [8]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, len(X_ds)):
  review = re.sub('[^a-zA-Z]', ' ', str(X_ds[i]))
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Varad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
print(corpus)

['come border kill', 'im get borderland kill', 'im come borderland murder', 'im get borderland murder', 'im get borderland murder', 'spent hour make someth fun know huge borderland fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg', 'spent coupl hour someth fun know huge borderland fan maya one favorit charact decid make wallpap pc origin pictur compar creation made fun pic twitter com mlsi wf jg', 'spent hour someth fun know huge borderland fan maya one favorit charact', 'spent hour make someth fun know huge rhandlerr fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg', 'spent hour make someth fun know huge rhandlerr fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg', '', 'rock hard la varlop rare power handsom jackpot borderland xbox dlvr rmtrgf', 'rock hard la varlop rare power handsom jac

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray() # type: ignore
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
ysy=lr.fit_transform(Y_ds)

In [12]:
print(lr.inverse_transform([0,1,2,3]))

['Irrelevant' 'Negative' 'Neutral' 'Positive']


In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,ysy,test_size=0.20,random_state=0)
print(x_train)

(1500,)


In [14]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)
y_pred=gb.predict(x_test)

In [15]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [1 1]
 [0 1]
 [3 3]
 [3 3]
 [3 3]
 [1 2]
 [3 3]
 [3 3]
 [0 3]
 [3 3]
 [3 3]
 [0 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [1 3]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [0 0]
 [3 3]
 [1 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 3]
 [2 2]
 [0 2]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [3 3]
 [1 1]
 [0 0]
 [2 2]
 [0 3]
 [3 3]
 [3 3]
 [0 3]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [2 3]
 [3 3]
 [3 3]
 [2 2]
 [0 0]
 [2 3]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [3 3]
 [0 3]
 [3 3]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 3]
 [0 0]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [1 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [2 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [1 2]
 [2 2]

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acs=accuracy_score(y_test,y_pred)
print(acs)

[[ 38   0   0   0]
 [  5  69   0   0]
 [  4   7 113   1]
 [ 19  13  14 174]]
0.862144420131291


In [17]:
input='Wine drunk playing the new Borderlands 😩'
data=[]
review = re.sub('[^a-zA-Z]', ' ', str(input))
review = review.lower()
review = review.split()
review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
review = ' '.join(review)
data.append(review)
print(data)

['wine drunk play new borderland']


In [18]:
new_Data=cv.transform(data).toarray()
print(new_Data)
print(gb.predict(new_Data))

[[0 0 0 ... 0 0 0]]
[2]


In [19]:
print(len(x_train))


1828


In [22]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [38]:
y_pred=lr.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score
acs=accuracy_score(y_test,y_pred)
print(acs)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.949671772428884
[[ 34   1   0   3]
 [  1  69   0   4]
 [  0   1 115   9]
 [  0   1   3 216]]


In [27]:
from sklearn.svm import SVC
sc=SVC(kernel='linear',random_state=0)
sc.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=sc.predict(x_test)
acs=accuracy_score(y_test,y_pred)
print(acs)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.9387308533916849
[[ 34   1   1   2]
 [  1  68   1   4]
 [  1   2 113   9]
 [  1   2   3 214]]


In [32]:
from sklearn.preprocessing import StandardScaler
scc=StandardScaler()
x_train2=scc.fit_transform(x_train)
x_test2=scc.transform(x_test)

In [36]:
lrr=LogisticRegression(random_state=0,max_iter=2000)
lrr.fit(x_train2,y_train)
y_pred=lrr.predict(x_test2)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score
acs=accuracy_score(y_test,y_pred)
print(acs)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.9518599562363238
[[ 34   2   0   2]
 [  0  70   0   4]
 [  0   1 118   6]
 [  0   3   4 213]]
